//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasketProduct
    {
        public int id_basket_product { get; set; }
        public Nullable<int> count { get; set; }
        public Nullable<int> id_product { get; set; }
        public Nullable<int> id_basket { get; set; }
    
        public virtual Basket Basket { get; set; }
        public virtual Products Products { get; set; }
    }
}
