//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reviews
    {
        public int id_rev { get; set; }
        public string user_rev { get; set; }
        public string rev_cons { get; set; }
        public string img_rev { get; set; }
    }
}
